#pragma once
#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define SCREEN_TITLE "AlTo"

#define MIN_SURGERY_CONSUMPTION 50
#define MAX_SURGERY_CONSUMPTION 400
#define AVG_PANEL_COST 300
#define MIN_PANEL_OUTPUT 1
#define MAX_PANEL_OUTPUT 4